name: Server Dev Branch CI

on:
  pull_request:
    branches:
      - server/dev

jobs:
  TESTING:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            ${{ runner.os }}-
            ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: MySQL setup
        uses: samin/mysql-action@v1
        with:
          mysql version: '8.0'
          mysql database: 'test_db'
          mysql user: ${{ secrets.DB_USER }}
          mysql password: ${{ secrets.DB_PASSWORD }}

      - name: yml 파일 생성
        run: |
          mkdir .common/src/main/resources && cd .common/src/main/resources
          touch ./application.yml
          echo "${{ secrets.APPLICATION_YML }}" > ./application.yml
        shell: bash

      - name: Run Test
        run: |
          gradle clean build